# Generated by Django 4.1 on 2022-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000)),
                ('date', models.DateField(null=True)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'comments',
                'verbose_name_plural': 'comments',
                'db_table': 'comments',
            },
        ),
    ]
