# Generated by Django 4.1 on 2022-08-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
