# Generated by Django 4.1 on 2022-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comments_options_remove_comments_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'comments', 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
