# Generated by Django 4.1 on 2022-08-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comments_options_comments_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
